# General Stettings
permalink: none

fullurl: 'http://beta.offenesparlament.de'

# Template Variables
title: 'offenes Parlament'
github_url: 'https://github.com/datenschule/offenesparlament.de'
twitter: '#'
contact: 'info@datenschule.de'